### PR TITLE
Add shebangs/change filenames/shorter variables in trash.py

### PR DESCRIPTION
**Pull request by notchtc**

### CODE REVIEW

**Review by indexerrowaty — COMMENTED** [review]
Idk if it's a good idea to minify trash.py code.

**Comment by notchtc** [comment]
Did you even check to commits, because it's not minification, and yeah it's my fault i worded the commit badly
@Indexerrowaty

**Comment by indexerrowaty** [comment]
h

**Review by indexerrowaty — APPROVED** [review]
Okay. This is not bad after all.

**Comment by indexerrowaty** [comment]
merge

**Pull request merged**
